services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/amd64
    container_name: jt-sql
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Mssql@2025
    ports:
      - "1434:1433" # host:container
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Mssql@2025' -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 60s

  api:
    build: .
    container_name: jt-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=JapaneseTrainerDb;User Id=sa;Password=Mssql@2025;TrustServerCertificate=True;
      - Jwt__Issuer=JapaneseTrainer
      - Jwt__Audience=JapaneseTrainerClient
      - Jwt__SecretKey=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  sql_data:
